# Generated by Django 3.1.4 on 2021-01-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_model',
            name='password',
        ),
    ]
