# Generated by Django 3.1.4 on 2021-01-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestSystem', '0001_initial'),
        ('TestCreation', '0007_auto_20210105_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_result', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCreation.teachertests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestSystem.signup_model')),
            ],
        ),
        migrations.CreateModel(
            name='StudAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosen_answer1', models.BooleanField(default=False)),
                ('choosen_answer2', models.BooleanField(default=False)),
                ('choosen_answer3', models.BooleanField(default=False)),
                ('choosen_answer4', models.BooleanField(default=False)),
                ('iscorrect', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebTesting.attempts')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCreation.questions')),
            ],
        ),
        migrations.AddField(
            model_name='attempts',
            name='passed_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebTesting.studtests'),
        ),
    ]
