# Generated by Django 3.1.4 on 2021-01-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=500, verbose_name='Название теста')),
                ('question_count', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestSystem.signup_model')),
            ],
        ),
    ]
