# Generated by Django 3.1.4 on 2021-01-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('question_number', models.IntegerField(default=0)),
                ('prompt', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCreation.teachertests')),
            ],
        ),
    ]
