# Generated by Django 3.1.4 on 2021-01-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreation', '0004_auto_20210104_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_number',
        ),
    ]
