# Generated by Django 3.1.4 on 2021-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreation', '0005_remove_questions_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default='answer', max_length=200, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default='answer', max_length=200, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default='answer', max_length=200, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default='answer', max_length=200, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='isright1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='isright2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='isright3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='isright4',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
