# Generated by Django 3.1.4 on 2021-01-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCreation', '0007_auto_20210105_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='manychoises',
            field=models.BooleanField(default=False),
        ),
    ]
